version: "3"
services:
  pg_master:
    container_name: pgmaster
    image: digitalorganic/pgmaster:2.0
    build: 
      context: ./master
      args: 
        - PG_DOCKER_BASE=${PG_DOCKER_BASE}
        - TZ=${TZ}
    volumes:
      - pg_master_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER}
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - "5431:5432"
    networks: 
      - pg_cluster

  pg_slave:
    container_name: pgslave
    image: digitalorganic/pgslave:2.0
    depends_on: 
      - pg_master
    build: 
      context: ./slave
      args: 
        - PG_DOCKER_BASE=${PG_DOCKER_BASE}
        - TZ=${TZ}
    ports: 
      - "5439:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER}
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=${POSTGRES_PASSWORD}
      - PG_MASTER_HOST=pg_master
      - SLAVE_NAME=s2
    volumes:
      - pg_slave_data:/var/lib/postgresql/data
    networks: 
      - pg_cluster

  pgpool:
    image: digitalorganic/pgpool:1.0
    build: 
      context: ./pgpool
    depends_on: 
      - pg_master
      - pg_slave
    environment:
      - PGPOOL_BACKENDS=1:pgmaster:5432,2:pgslave:5432
    ports:
      - 5430:5432/tcp
    networks:
      - pg_cluster
        
      
volumes:
  pg_master_data:
  pg_slave_data:

networks:
  pg_cluster:
    external: true